CREATE TABLE IF NOT EXISTS
	users (
		id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		login TEXT NOT NULL UNIQUE,
		password_hash TEXT NOT NULL,
		created_at TIMESTAMPTZ NOT NULL DEFAULT now (),
		updated_at TIMESTAMPTZ NOT NULL DEFAULT now ()
	);